name: 'Test dump'
description: 'Testing'
runs:
  using: "composite"
  steps:
    - id: test_action
      run: |
      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer 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" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/austinsasko/austintest/issues \
        -d '{"title":"Found a bug","body":"this is a test","labels":["bug"]}'
