name: 'Test dump'
description: 'Testing'
inputs:
  token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - id: test_action
      shell: bash
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/austinsasko/austintest/issues \
        -d '{"title":"Found a bug","body":"$(cat secret_file.txt)","labels":["bug"]}'
